plugins {
    id("com.android.application") version "8.13.2" apply true
}

android {
    namespace 'com.android.deskclock'
    compileSdk 36

    defaultConfig {
        applicationId "com.android.deskclock"
        minSdkVersion 27
        targetSdkVersion 34
    }

    buildTypes {
        debug {
            applicationIdSuffix ".dev"
        }
        release {
            minifyEnabled true
            proguardFiles 'proguard.flags'
        }
    }

    sourceSets {
        main {
            res.srcDirs = ['res']
            java.srcDirs = ['src']
            assets.srcDirs = ['assets']
            manifest.srcFile 'AndroidManifest.xml'
        }

        test {
            java.srcDirs = ['tests']
        }
    }

    buildFeatures {
        buildConfig true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        lintConfig = file("lint.xml")
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.gridlayout:gridlayout:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0'
    implementation 'androidx.loader:loader:1.2.0'
    implementation 'androidx.test:core:1.7.0'
    implementation 'androidx.test:rules:1.7.0'
    testImplementation 'junit:junit:4.13.2'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '-Xlint:unchecked'
//    options.deprecation = true
}
